#+title: Конфигурация GNU Emacs
#+author: Клементьев Дмитрий
#+email: klementievd08@yandex.ru

Главные цели данной конфигурации:
- Удобная навигация по =Emacs.org=
- Относительно быстрое время запуска (даже при использовании =org-babel=)
- Простая кодовая база (понятная и читаемая)
- Лишь несколько основных пакетов загружаются на старте (ленивая загрузка)
- Отсутствие =use-package= макроса
- Почти идеальная поддержка терминала (=emacs -nw=)

Прочие файлы:
- [[file:early-init.el][Файл ранней инициализации]] - Большая часть оптимизаций
- [[file:init.el][Файл инициализации]] - Загружает org файл

Флаг в начале файла для байт-компиляции.

#+begin_src emacs-lisp
  ;;; -*- lexical-binding: t; -*-
#+end_src

* Макросы, функции и прочие хелпер фиговины для моего конфига

Некоторые вещи для данной конфигурации приходится изобретать с полного нуля

** Макросы упрощающие ленивую загрузку

Это небольшой набор моих собственных макросов для ленивой загрузки (на подобии Neovim).

Вся суть в том, что я не использую =use-package= (он мне не нравится), вместо этого я использую
другой встроенный в Emacs функционал:
- =autoload=
- =with-eval-after-load=
- =eval-when-compile=

А так же набор своих макросов.

*** =require-on!= - Загрузка пакета на хуке/комманде

#+begin_src emacs-lisp
  (defun require-on-hook (hook package)
    (let ((fnname (intern (concat "load-" (prin1-to-string package)
                                  "-on-" (prin1-to-string hook)))))
      `(when (boundp ',hook)
         ,(unless (fboundp fnname)
            `(defun ,fnname (&rest _)
               (require ',package)
               (remove-hook ',hook #',fnname)))
         (add-hook ',hook #',fnname))))

  (defun require-on-command (command package)
    (let ((fnname (intern (concat "load-" (prin1-to-string package)))))
      `(when (fboundp ',command)
         (define-advice ,command
             (:before (&rest _) ,fnname)
           (advice-remove ',command #',(intern (concat (prin1-to-string command)
                                                       "@" (prin1-to-string fnname))))
           (require ',package)))))

  (defmacro require-on! (symbol package)
    "Load PACKAGE on SYMBOL."
    (declare (indent defun))
    (cond
     ((commandp symbol)
      (require-on-command symbol package))
     ((boundp symbol)
      (require-on-hook symbol package))
     (t (error "Can't determine symbol for require-on!: %s" symbol))))
#+end_src

* Базовая настройка GNU Emacs

В этой части я настраиваю базовый GNU Emacs.

#+begin_src emacs-lisp
  (defun load-my-custom-file ()
    (load custom-file :no-error :no-message :no-suffix :must-suffix))

  (with-eval-after-load 'emacs
    (add-hook 'after-init-hook #'load-my-custom-file)

    (setq-default frame-title-format "GNU Emacs"
                  make-backup-files nil
                  custom-file (expand-file-name "custom.el"
                                                user-emacs-directory)
                  cursor-type '(bar . 2)
                  cursor-in-non-selected-windows nil
                  default-input-method "russian-computer"
                  indent-tabs-mode nil
                  tab-width 4)

    (global-visual-line-mode 1))
#+end_src

** Встроенные модули

#+begin_src emacs-lisp
  (eval-when-compile
    (require 'which-key)
    (require 'recentf)
    (require 'fringe))

  (with-eval-after-load 'jsonrpc
    (fset #'jsonrpc--log-event #'ignore))

  (with-eval-after-load 'recentf
    (add-hook 'emacs-startup-hook 'recentf-mode))

  (with-eval-after-load 'which-key
    (add-hook 'emacs-startup-hook 'which-key-mode))

  (with-eval-after-load 'fringe
    (fringe-mode '(8 . 8)))
#+end_src

* Внешний вид

Здесь мы настраиваем основную часть внешнего вида GNU Emacs.

| *Основная тема*    | Doom One     |
| *Строка состояния* | Awesome Tray |

** Основная тема (doom themes)

#+begin_src emacs-lisp
  (elpaca 'doom-themes
    (autoload 'doom-one "doom-themes")
    (add-hook 'emacs-startup-hook
              (lambda ()
                (load-theme 'doom-one :no-confirm)))
    (add-hook 'after-make-frame-functions
              (lambda (frame)
                (with-selected-frame frame
                  (load-theme 'doom-one :no-confirm)))))
#+end_src

** Строка состояния

#+begin_src emacs-lisp :no-export
  (setq-default awesome-tray-hide-mode-line t)
  (elpaca '(awesome-tray
            :host github
            :repo "manateelazycat/awesome-tray")
    (autoload 'awesome-tray-mode "awesome-tray")
    (add-hook 'emacs-startup-hook 'awesome-tray-mode 103))
#+end_src

** Начальный экран

В качестве начального экрана есть два пакета:
- =dashboard= - Максимально простой и готов к использованию
- =enlight= + =grid= - Очень глубокая кастомизация (сложен в настройке)

Пока что я выберу Dashboard, и не буду париться о том, что и как нужно
делать.

#+begin_src emacs-lisp
  (setq-default dashboard-center-content t
                dashboard-vertically-center-content t
                dashboard-items '((recents . 10)
                                  (bookmarks . 3)
                                  (projects . 3)
                                  (agenda . 5)))
  (elpaca 'dashboard
    (autoload 'dashboard-setup-startup-hook "dashboard")
    (dashboard-setup-startup-hook))

  (with-eval-after-load 'dashboard
    ;; Open dashboard when using "emacsclient -c" (daemon only)
    (when (daemonp)
      (setq initial-buffer-choice (get-buffer-create dashboard-buffer-name))))
#+end_src

* Vertico + Marginalia + Orderless

#+begin_src emacs-lisp
  (elpaca 'vertico
    (require-on! pre-command-hook
      vertico))

  (elpaca 'marginalia
    (with-eval-after-load 'vertico
      (require 'marginalia)))

  (with-eval-after-load 'marginalia
    (marginalia-mode 1))

  (with-eval-after-load 'vertico
    (vertico-mode 1))

  (elpaca 'orderless
    (require-on! pre-command-hook
      orderless))

  (with-eval-after-load 'orderless
    (setq completion-styles '(orderless basic)))
#+end_src

* Consult

#+begin_src emacs-lisp
  (elpaca 'consult
    (eval-when-compile
      (require 'consult)))

  (with-eval-after-load 'consult
    (bind-keys ("s-B" . consult-buffer)
               ([remap switch-to-buffer] . consult-buffer)
               ("C-s" . consult-line)
               ("M-g g" . consult-goto-line)))
#+end_src

* Навигация

Данный заголовок включает в себя конфигурацию которая относится к навигации между окнами, в тексте, и.т.д

** Навигация в тексте

Для навигации в тексте есть множество плагинов:
- =avy= - Основной плагин (и пока что единственный используемый в конфиге)
- =ace-link= - Как =ace-window= или =avy=, но для ссылок
- и.т.д - TODO: Пакетов еще много, их стоит разобрать

Конфигурация =avy=.

TODO: Стоит посмотреть ещё комманды которые предоставляет =avy=. (Это слишком мощная штука)

#+begin_src emacs-lisp
  (elpaca 'avy
    (autoload 'avy-goto-char-2 "avy")
    (bind-key* "C-'" 'avy-goto-char-2))
#+end_src

** Навигация между окнами

Идеальную навигацию между окнами обеспечивают два плагина:
- =golden-ratio= - Автоматически изменяет размер окна
- =ace-window= - Удобное перемещение между окнами одной клавишей (=M-o=)

#+begin_src emacs-lisp
  (elpaca 'ace-window
    (autoload 'ace-window "ace-window")
    (bind-key "M-o" 'ace-window))
#+end_src

=golden-ratio= будет подгружаться при разделении окна (горизонтально или вертикально).

После чего мы добавляем функцию которая будет запускаться после =ace-window=, и будет
устанавливать размер окна в соответствии с =golden-ratio=. Это нужно лишь потому, что
=golden-ratio= почему то не работает с =ace-window= по дефолту.

#+begin_src emacs-lisp
  (elpaca 'golden-ratio
    (require-on! split-window-below
      golden-ratio)
    (require-on! split-window-right
      golden-ratio))

  (with-eval-after-load 'golden-ratio
    (golden-ratio-mode 1)
    (with-eval-after-load 'ace-window
      (define-advice ace-window
          (:after (&rest _) golden-ratio)
        (golden-ratio))))
#+end_src

* Org Mode

*Org* - основная часть GNU Emacs. Данный пакет - причина по которой я не могу уйти от GNU Emacs.

** Базовая и обязательная настройка

- Табуляция заголовков (=org-indent-mode=)
- Навигация при помощи =consult-outline=

#+begin_src emacs-lisp
  (add-hook 'org-mode-hook 'org-indent-mode)

  (with-eval-after-load 'org
    (with-eval-after-load 'consult
      (bind-keys :map org-mode-map
                 ("C-s" . consult-outline)
                 ("C-S-s" . consult-line))))
#+end_src

** Agenda

TODO: Использовать =org-super-agenda=

*** Кастомные комманды, виды (Custom commands, views)

**** Learning (Обучение)

Отдельный вид агенды для отслеживания и планирования задач, целей по изучению алгоритмов
и структур данных

#+begin_src emacs-lisp :tangle no :noweb-ref custom-agenda-views
  ("l" "Learning Agenda"
   ((agenda "" ((org-agenda-span 'day)
                (org-agenda-remove-tags t)
                (org-deadline-warning-days 7)
                ;; TODO: Filter by @yandexlearning tag instead of file
                (org-agenda-files '("~/org/agenda/YandexLearning.org"))))
    (tags-todo "+@yandexlearning+PRIORITY=\"A\"+SCHEDULED<=\"<today>\""
               ((org-agenda-span 'day)
                (org-agenda-remove-tags t)
                (org-agenda-overriding-header "High Priority Tasks")))
    (tags-todo "+@yandexlearning/TODO"
               ((org-agenda-tags-todo-honor-ignore-options t)
                (org-agenda-todo-ignore-scheduled t)
                (org-agenda-remove-tags t)
                (org-agenda-overriding-header "Just TODO Tasks")))))
#+end_src

**** Weekly Review (Недельный обзор)

Недельный обзор завершённых и оставшихся запланированных задач.

Неплохо посмотреть в конце недели как много ты проеб\*\*нил :)

#+begin_src emacs-lisp :tangle no :noweb-ref custom-agenda-views
  ("w" "Weekly Review"
   ((agenda "" ((org-agenda-overriding-header "Completed Tasks")
                (org-agenda-skip-function '(org-agenda-skip-entry-if 'nottodo 'done))
                (org-agenda-span 'week)))
    (agenda "" ((org-agenda-overriding-header "Unfinished Scheduled Tasks")
                (org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                (org-agenda-span 'week)))))
#+end_src

*** Конфигурация

#+begin_src emacs-lisp :noweb yes :noweb-prefix no
  (setq-default org-agenda-custom-commands '(<<custom-agenda-views>>))
#+end_src

#+begin_src emacs-lisp
  (setq-default org-agenda-start-with-log-mode t
                org-log-done 'time
                org-log-into-drawer t)

  (define-advice org-agenda
      (:before (&rest _) update-files)
    (setq org-agenda-files
          (directory-files-recursively
           (expand-file-name "agenda" org-directory)
           "\\`[A-Za-z]*.org\\'")))

  (bind-key "a" 'org-agenda mode-specific-map)
#+end_src

* Системы контроля версий (Git интеграция)

Git интеграция сводится в основном к двум плагинам: =magit= и =forge=.

=magit= - Незаменимый и безальтернативный Git интерфейс. Более мощного гит интерфейса вы просто не найдёте.

=forge= - Клиент для Github, Gitlab и других хостингов прямо в GNU Emacs.

Пока что я не устанавливаю Forge в своей конфигурации (он мне попросту не нужен, а так же я пишу её не
на своём устройстве). Зато мы сделаем конфиг для Git файлов (gitattributes, gitignore, gitsubmodules)
и настроим Magit, который будет показывать для нас TODOs (плагин =magit-todos=)

#+begin_src emacs-lisp
  (elpaca '(transient
            :host github
            :repo "magit/transient"
            :tag "v0.9.3"))

  (elpaca magit
    (autoload 'magit "magit")
    (bind-key "C-x g" 'magit))
#+end_src

** Magit TODOs

Плагин который отлично выводит все *TODO* ключевые слова.

#+begin_src emacs-lisp
  (elpaca 'magit-todos
    (autoload 'magit-todos-mode "magit-todos")
    (add-hook 'magit-mode-hook 'magit-todos-mode))
#+end_src

** Git файлы и режимы для них

#+begin_src emacs-lisp
  (elpaca 'git-modes
    (autoload 'gitignore-mode "git-modes")
    (autoload 'gitconfig-mode "git-modes")
    (autoload 'gitattributes-mode "git-modes")
    (setq auto-mode-alist
          (append
           '((".gitignore\\'" . gitignore-mode)
             (".gitconfig\\'" . gitconfig-mode)
             (".gitattributes\\'" . gitattributes-mode))
           auto-mode-alist)))
#+end_src
