= Emacs Workflowww
Klementiev Dmitry <klementievd08@yandex.ru>
:toc: 1


== Supported Languages

* Go
* Bash


NOTE: Also I can add following languages in the future: C, C++, Python, Rust.


== Supported Markup languages

Currently I working only with following tools:

* LaTeX
* AsciiDoc (`asciidoctor`/`asciidoxy`)

Sometimes I writing in *Org Mode* (for myself only). I would like to learn *LaTeX* and *AsciiDoc* first.

NOTE: Also I can add following markup languages in the future: reStructuredText, Markdown, Org Mode

=== AsciiDoc tools

AsciiDoc has following tools:

* `asciidoctor` - AsciiDoc "compilator" written in Ruby
* `asciidoxy` - AsciiDoc "compilator" written in Python


For just markup, simple html page and etc you can use `asciidoctor`. But if you want better documentation written in AsciiDoc format, look at `asciidoxy`. `asciidoxy` is something like Sphinx for reStructuredText files.

=== LaTeX tools

For latex I have following tools:

* `pdflatex` - Default thing for me
* `lualatex` - Use it for system-wide fonts only =)
* `xelatex`  - lualatex alternative which I don't use


All my LaTeX documentation compiled by `pdflatex`. I use `lualatex` only for Resume/CV pdf compilation (because I use system-wide fonts with russian language support).

== System Dependencies

* `mu`          - Mail client
* `ripgrep`     - Faster grep alternative
* `python`      - Python =)
* `git`         - Main VCS
* `asciidoctor` - AsciiDoc Ctor
* `go`          - It's my main language
* `lualatex`    - PDFs writing
* `make`        - M-x compile
