#+title: simple todolist

* TODO Сделать свой пакет для настройки Eshell.

При изучении и настройке Eshell я понял насколько это безгранично, но и муторно. Можно сделать
пакет, который упростит этот процесс.

* TODO Более каноничное разбиение файлов.

Сейчас в файле =bootstrap.el= у меня находиться следующие вещи:
- =process-await= - простая функция для так скажем awaiting'а процесса (просто цикл, который проверяет "жив" ли процесс)
- =install-adwaita-mono-nerd= - Асинхронная функция для установки нужного шрифта.
- =user-themes= - Надо будет разобрать это попозже =)


В целом, исходный код нужно перебрать до добавления нового функционала, чтобы потом не было так, что проще переписать, чем разбирать это.

* TODO Сделать более лучшую загрузку шрифта.

Идея довольно простая.

1. При запуске GNU Emacs загружать обычный шрифт "Adwaita Mono".
2. Далее в отдельном потоке запускаем ожидание установки, после чего устанавливаем этот шрифт вместо основного.


Таким образом пользователь даже не заметит установки шрифта (если конечно не наткнётся на иконки, которые будут отображаться неправильно
без пропатченного шрифта).


Сейчас пользователю скорее всего придётся ждать при загрузке GNU Emacs. Т.к если при запущенном Emacs шрифты еще не установлены, он начнёт ожидать их установку
в основном потоке.
